SQL_DATABASE_PATH: str = "data/football.db"
# MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
MODEL_ID = "mistralai/Mistral-7B-Instruct-v0.3"
MODEL_END_TOKEN = "[/INST]"
MODEL_INIT_TOKEN = "[INST]"
DEFAULT_BOT_MESSAGE = "I'm an assistant which can help you get insights on football matches (National teams level) based on historical data from Official FIFA matches"
